title: Anubhav Srivastava
description: Portfolio

collections:
  blog:
    output: true
    permalink: /blog/:slug/

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

minima:
  skin: dark