title: Anubhav Srivastava
description: Personal Website

author:
  name: Anubhav Srivastava

url: "https://deltadynamo.github.io"
baseurl: ""

collections:
  blog:
    output: true
    permalink: /blog/:slug/

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

header_pages:
  - blog.md

minima:
  skin: dark

  include:
    - head-custom.html

  date_format: "%Y-%m-%d"

  social_links:
    - title: Github
      icon: github
      url: "https://github.com/DeltaDynamo"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/anubhavsrivastavain"
