title: Anubhav Srivastava
description: Portfolio

collections:
  blog:
    output: true
    permalink: /blog/:slug/

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
  rouge:
    css: 'monokai'

############################################
#remote_theme: pages-themes/architect@v0.2.0
#plugins:
#  - jekyll-remote-theme
