title: Anubhav Srivastava
description: Personal Website

author:
  name: Anubhav Srivastava

collections:
  blog:
    output: true
    permalink: /blog/:slug/

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

header_pages:
  - blog.md

minima:
  skin: dark

  date_format: "%b-%d-%Y"

  social_links:
    - { platform: github,         user_url: "https://github.com/DeltaDynamo" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/anubhavsrivastavain" }