title: Anubhav Srivastava
description: Portfolio

collections:
  blog:
    output: true
    permalink: /blog/:slug/

############################################
#remote_theme: pages-themes/architect@v0.2.0
#plugins:
#  - jekyll-remote-theme
